# -*- coding: utf-8 -*-
"""协议层常量（不 import 网易）。

所有 payload 必须带 protocolVersion。
"""

PROTOCOL_VERSION = 1

# 消息类型
MARKET_SUMMARY_REQ = "MARKET_SUMMARY_REQ"
MARKET_SUMMARY_RES = "MARKET_SUMMARY_RES"
QUOTE_BUY_REQ = "QUOTE_BUY_REQ"
QUOTE_BUY_RES = "QUOTE_BUY_RES"
QUOTE_SELL_REQ = "QUOTE_SELL_REQ"
QUOTE_SELL_RES = "QUOTE_SELL_RES"
CONFIRM_QUOTE_REQ = "CONFIRM_QUOTE_REQ"
CONFIRM_QUOTE_RES = "CONFIRM_QUOTE_RES"
CREATE_ORDER_REQ = "CREATE_ORDER_REQ"
CREATE_ORDER_RES = "CREATE_ORDER_RES"
CANCEL_ORDER_REQ = "CANCEL_ORDER_REQ"
CANCEL_ORDER_RES = "CANCEL_ORDER_RES"
MY_ORDERS_REQ = "MY_ORDERS_REQ"
MY_ORDERS_RES = "MY_ORDERS_RES"
CLAIMS_REQ = "CLAIMS_REQ"
CLAIMS_RES = "CLAIMS_RES"
CLAIM_REQ = "CLAIM_REQ"
CLAIM_RES = "CLAIM_RES"
ERROR_RES = "ERROR_RES"

# 请求消息类型集合
KNOWN_REQUEST_TYPES = {
    MARKET_SUMMARY_REQ,
    QUOTE_BUY_REQ,
    QUOTE_SELL_REQ,
    CONFIRM_QUOTE_REQ,
    CREATE_ORDER_REQ,
    CANCEL_ORDER_REQ,
    MY_ORDERS_REQ,
    CLAIMS_REQ,
    CLAIM_REQ,
}

# 消息字段
FIELD_PROTOCOL_VERSION = "protocolVersion"
FIELD_TYPE = "type"
FIELD_ITEM_ID = "itemId"
FIELD_AMOUNT = "amount"
FIELD_UNIT_PRICE = "unitPrice"
FIELD_QUOTE_ID = "quoteId"
FIELD_ORDER_ID = "orderId"
FIELD_CLAIM_ID = "claimId"
FIELD_SIDE = "side"

# 服务端权威字段：客户端传入一律忽略（服务端自己算）。
SERVER_AUTHORITATIVE_FIELDS = {
    "price", "balance", "stock", "fee", "tax", "marketVersion",
}
